style_guide:
  sections:
    branding:
      icon: "flag"
    components:
      icon: "cubes"
    css_guide:
      icon: "code"
    ux_guide:
      icon: "user"
    visual_elements:
      icon: "pencil"
    voice_and_tone:
      icon: "bullhorn"
